# companies.yml
# Add/remove companies easily. Find their board provider and slug:
# - Greenhouse: https://boards.greenhouse.io/<slug>
# - Lever: https://jobs.lever.co/<slug>
#
# Include/exclude keywords are optional. If omitted, sensible defaults are used.

companies:
  # --- Greenhouse (GH) ---
  - {name: Datadog,          provider: greenhouse, slug: datadog, include_keywords: [], exclude_keywords: []}
  - {name: HubSpot,          provider: greenhouse, slug: hubspot, include_keywords: [], exclude_keywords: []}
  - {name: Wayfair,          provider: greenhouse, slug: wayfair, include_keywords: [], exclude_keywords: []}
  - {name: Robin Powered,      provider: greenhouse, slug: robinpowered, include_keywords: [], exclude_keywords: []}
  - {name: Perceptive Automata, provider: greenhouse, slug: perceptiveautomata, include_keywords: [], exclude_keywords: []}
  - {name: Tulip Interfaces,   provider: greenhouse, slug: tulipinterfaces, include_keywords: [], exclude_keywords: []}

  # --- Lever ---

# Expand this list with other Boston/remote-friendly companies on Greenhouse/Lever:
# Akamai (custom career site), MathWorks (Workday), Amazon Robotics (Workday), NVIDIA (Greenhouse: nvidia),
# Two Sigma (Greenhouse: twosigma), Jane Street (Greenhouse: janestreet), etc.
# If a company isn't on Greenhouse/Lever, you'll need a custom fetcher.

# Locations considered "Boston area"
boston_locations:
  - Boston
  - Cambridge
  - Somerville
  - Lexington
  - Needham
  - Waltham
  - Watertown
  - Brookline
  - Newton
  - Burlington
  - Quincy
  - Norwood

# Global flags
include_remote: true
out_dir: ./reports
